<?php
/**
 * @file
 * laurapartners.features.field.inc
 */

/**
 * Implements hook_field_default_fields().
 */
function laurapartners_field_default_fields() {
  $fields = array();

  // Exported field: 'node-our_partners-body'.
  $fields['node-our_partners-body'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(
        0 => 'node',
      ),
      'field_name' => 'body',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'locked' => '0',
      'module' => 'text',
      'settings' => array(),
      'translatable' => '0',
      'type' => 'text_with_summary',
    ),
    'field_instance' => array(
      'bundle' => 'our_partners',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => '0',
        ),
        'teaser' => array(
          'label' => 'hidden',
          'module' => 'text',
          'settings' => array(
            'trim_length' => '300',
          ),
          'type' => 'text_summary_or_trimmed',
          'weight' => '0',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'body',
      'label' => 'Description of Partnership',
      'required' => 0,
      'settings' => array(
        'display_summary' => 1,
        'text_processing' => '1',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'rows' => '50',
          'summary_rows' => 5,
        ),
        'type' => 'text_textarea_with_summary',
        'weight' => '2',
      ),
    ),
  );

  // Exported field: 'node-our_partners-field_address'.
  $fields['node-our_partners-field_address'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_address',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(),
      'indexes' => array(),
      'locked' => '0',
      'module' => 'addressfield',
      'settings' => array(),
      'translatable' => '0',
      'type' => 'addressfield',
    ),
    'field_instance' => array(
      'bundle' => 'our_partners',
      'default_value' => array(
        0 => array(
          'element_key' => 'node|our_partners|field_address|und|0',
          'thoroughfare' => '',
          'premise' => '',
          'locality' => '',
          'administrative_area' => '',
          'postal_code' => '',
          'country' => 'CA',
        ),
      ),
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'addressfield',
          'settings' => array(
            'format_handlers' => array(
              0 => 'address',
            ),
            'use_widget_handlers' => 1,
          ),
          'type' => 'addressfield_default',
          'weight' => '3',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '7',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_address',
      'label' => 'Address',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'addressfield',
        'settings' => array(
          'available_countries' => array(),
          'format_handlers' => array(
            'address' => 'address',
            'address-hide-country' => 0,
            'organisation' => 0,
            'name-full' => 0,
            'name-oneline' => 0,
          ),
        ),
        'type' => 'addressfield_standard',
        'weight' => '7',
      ),
    ),
  );

  // Exported field: 'node-our_partners-field_email'.
  $fields['node-our_partners-field_email'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_email',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(),
      'indexes' => array(),
      'locked' => '0',
      'module' => 'email',
      'settings' => array(),
      'translatable' => '0',
      'type' => 'email',
    ),
    'field_instance' => array(
      'bundle' => 'our_partners',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'email',
          'settings' => array(),
          'type' => 'email_default',
          'weight' => 8,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_email',
      'label' => 'Email',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'email',
        'settings' => array(
          'size' => '100',
        ),
        'type' => 'email_textfield',
        'weight' => '5',
      ),
    ),
  );

  // Exported field: 'node-our_partners-field_industry'.
  $fields['node-our_partners-field_industry'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '-1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_industry',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'tid' => array(
          'columns' => array(
            'tid' => 'tid',
          ),
          'table' => 'taxonomy_term_data',
        ),
      ),
      'indexes' => array(
        'tid' => array(
          0 => 'tid',
        ),
      ),
      'locked' => '0',
      'module' => 'taxonomy',
      'settings' => array(
        'allowed_values' => array(
          0 => array(
            'vocabulary' => 'industry',
            'parent' => '0',
          ),
        ),
      ),
      'translatable' => '0',
      'type' => 'taxonomy_term_reference',
    ),
    'field_instance' => array(
      'bundle' => 'our_partners',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'taxonomy',
          'settings' => array(),
          'type' => 'taxonomy_term_reference_link',
          'weight' => '5',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '5',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_industry',
      'label' => 'Industry',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'taxonomy',
        'settings' => array(
          'autocomplete_path' => 'taxonomy/autocomplete',
          'size' => 60,
        ),
        'type' => 'taxonomy_autocomplete',
        'weight' => '4',
      ),
    ),
  );

  // Exported field: 'node-our_partners-field_logo'.
  $fields['node-our_partners-field_logo'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_logo',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'fid' => array(
          'columns' => array(
            'fid' => 'fid',
          ),
          'table' => 'file_managed',
        ),
      ),
      'indexes' => array(
        'fid' => array(
          0 => 'fid',
        ),
      ),
      'locked' => '0',
      'module' => 'image',
      'settings' => array(
        'default_image' => 0,
        'uri_scheme' => 'public',
      ),
      'translatable' => '0',
      'type' => 'image',
    ),
    'field_instance' => array(
      'bundle' => 'our_partners',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'image',
          'settings' => array(
            'image_link' => '',
            'image_style' => '',
          ),
          'type' => 'image',
          'weight' => '2',
        ),
        'teaser' => array(
          'label' => 'above',
          'module' => 'image',
          'settings' => array(
            'image_link' => '',
            'image_style' => 'thumbnail',
          ),
          'type' => 'image',
          'weight' => '1',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_logo',
      'label' => 'Logo',
      'required' => 0,
      'settings' => array(
        'alt_field' => 1,
        'default_image' => 0,
        'file_directory' => '',
        'file_extensions' => 'png gif jpg jpeg',
        'max_filesize' => '4 MB',
        'max_resolution' => '50x50',
        'min_resolution' => '300x300',
        'title_field' => 1,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'image',
        'settings' => array(
          'aviary_feather_enabled' => 0,
          'aviary_feather_position' => '0',
          'filefield_sources' => array(
            'filefield_sources' => array(
              'attach' => 0,
              'clipboard' => 0,
              'imageeditor' => 0,
              'plupload' => 0,
              'reference' => 0,
              'remote' => 0,
            ),
            'source_attach' => array(
              'absolute' => '0',
              'attach_mode' => 'move',
              'path' => 'file_attach',
            ),
            'source_imageeditor' => array(
              'source_imageeditor_image' => 0,
            ),
            'source_imce' => array(
              'imce_mode' => 0,
            ),
            'source_reference' => array(
              'autocomplete' => '0',
            ),
          ),
          'flauntr_styler_enabled' => 0,
          'flauntr_styler_position' => '0',
          'fotoflexer_enabled' => 0,
          'fotoflexer_position' => '0',
          'imageeditor_icons_position' => '0',
          'imageeditor_inline_revert_enabled' => 0,
          'imageeditor_inline_revert_position' => '0',
          'imageeditor_replace' => 0,
          'imageshack_upload_enabled' => 0,
          'imageshack_upload_position' => '0',
          'immio_upload_enabled' => 0,
          'immio_upload_position' => '0',
          'insert' => 0,
          'insert_absolute' => 0,
          'insert_class' => '',
          'insert_default' => 'link',
          'insert_styles' => array(
            'auto' => 'auto',
            'colorbox__cheap_dropshadow' => 0,
            'colorbox__corners_combo' => 0,
            'colorbox__default' => 0,
            'colorbox__keyword_positioning' => 0,
            'colorbox__large' => 0,
            'colorbox__medium' => 0,
            'colorbox__positioned_underlay' => 0,
            'colorbox__relative_canvas' => 0,
            'colorbox__rotate_alpha' => 0,
            'colorbox__rotate_alpha_gif' => 0,
            'colorbox__rotate_scale' => 0,
            'colorbox__rotate_scale_alpha' => 0,
            'colorbox__rounded' => 0,
            'colorbox__rounded_bl' => 0,
            'colorbox__rounded_flattened' => 0,
            'colorbox__scale' => 0,
            'colorbox__scale_canvas' => 0,
            'colorbox__scale_rotate' => 0,
            'colorbox__thumbnail' => 0,
            'colorbox__watermark_100' => 0,
            'colorbox__watermark_50' => 0,
            'icon_link' => 0,
            'image' => 0,
            'image_cheap_dropshadow' => 0,
            'image_corners_combo' => 0,
            'image_default' => 0,
            'image_keyword_positioning' => 0,
            'image_large' => 0,
            'image_medium' => 0,
            'image_positioned_underlay' => 0,
            'image_relative_canvas' => 0,
            'image_rotate_alpha' => 0,
            'image_rotate_alpha_gif' => 0,
            'image_rotate_scale' => 0,
            'image_rotate_scale_alpha' => 0,
            'image_rounded' => 0,
            'image_rounded_bl' => 0,
            'image_rounded_flattened' => 0,
            'image_scale' => 0,
            'image_scale_canvas' => 0,
            'image_scale_rotate' => 0,
            'image_thumbnail' => 0,
            'image_watermark_100' => 0,
            'image_watermark_50' => 0,
            'link' => 0,
          ),
          'insert_width' => '',
          'paintweb_enabled' => 0,
          'paintweb_position' => '0',
          'picmonkey_enabled' => 0,
          'picmonkey_position' => '0',
          'pixlr_editor_enabled' => 0,
          'pixlr_editor_position' => '0',
          'pixlr_express_enabled' => 0,
          'pixlr_express_position' => '0',
          'pixlr_upload_enabled' => 0,
          'pixlr_upload_position' => '0',
          'preview_image_style' => 'thumbnail',
          'progress_indicator' => 'throbber',
          'snipshot_enabled' => 0,
          'snipshot_position' => '0',
          'sumopaint_enabled' => 0,
          'sumopaint_position' => '0',
          'svgedit_enabled' => 0,
          'svgedit_position' => '0',
        ),
        'type' => 'image_image',
        'weight' => '3',
      ),
    ),
  );

  // Exported field: 'node-our_partners-field_phone_number'.
  $fields['node-our_partners-field_phone_number'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '2',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_phone_number',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(),
      'indexes' => array(),
      'locked' => '0',
      'module' => 'phone',
      'settings' => array(
        'country' => 'ca',
      ),
      'translatable' => '0',
      'type' => 'phone',
    ),
    'field_instance' => array(
      'bundle' => 'our_partners',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'phone',
          'settings' => array(),
          'type' => 'phone',
          'weight' => '4',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '6',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_phone_number',
      'label' => 'Phone Number',
      'required' => 0,
      'settings' => array(
        'ca_phone_parentheses' => 1,
        'ca_phone_separator' => '-',
        'phone_country_code' => 0,
        'phone_default_country_code' => '1',
        'phone_int_max_length' => 15,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'phone',
        'settings' => array(),
        'type' => 'phone_textfield',
        'weight' => '8',
      ),
    ),
  );

  // Exported field: 'node-our_partners-field_screenshot'.
  $fields['node-our_partners-field_screenshot'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_screenshot',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'fid' => array(
          'columns' => array(
            'fid' => 'fid',
          ),
          'table' => 'file_managed',
        ),
      ),
      'indexes' => array(
        'fid' => array(
          0 => 'fid',
        ),
      ),
      'locked' => '0',
      'module' => 'image',
      'settings' => array(
        'default_image' => 0,
        'uri_scheme' => 'public',
      ),
      'translatable' => '0',
      'type' => 'image',
    ),
    'field_instance' => array(
      'bundle' => 'our_partners',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'image',
          'settings' => array(
            'image_link' => '',
            'image_style' => '',
          ),
          'type' => 'image',
          'weight' => 9,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_screenshot',
      'label' => 'Screenshot',
      'required' => 0,
      'settings' => array(
        'alt_field' => 1,
        'default_image' => 0,
        'file_directory' => '',
        'file_extensions' => 'png gif jpg jpeg',
        'max_filesize' => '10 MB',
        'max_resolution' => '100x100',
        'min_resolution' => '2000x2000',
        'title_field' => 1,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'image',
        'settings' => array(
          'aviary_feather_enabled' => 0,
          'aviary_feather_position' => '0',
          'filefield_sources' => array(
            'filefield_sources' => array(
              'attach' => 0,
              'clipboard' => 0,
              'imageeditor' => 0,
              'plupload' => 0,
              'reference' => 0,
              'remote' => 0,
            ),
            'source_attach' => array(
              'absolute' => '0',
              'attach_mode' => 'move',
              'path' => 'file_attach',
            ),
            'source_imageeditor' => array(
              'source_imageeditor_image' => 0,
            ),
            'source_imce' => array(
              'imce_mode' => 0,
            ),
            'source_reference' => array(
              'autocomplete' => '0',
            ),
          ),
          'flauntr_styler_enabled' => 0,
          'flauntr_styler_position' => '0',
          'fotoflexer_enabled' => 0,
          'fotoflexer_position' => '0',
          'imageeditor_icons_position' => '0',
          'imageeditor_inline_revert_enabled' => 0,
          'imageeditor_inline_revert_position' => '0',
          'imageeditor_replace' => 0,
          'imageshack_upload_enabled' => 0,
          'imageshack_upload_position' => '0',
          'immio_upload_enabled' => 0,
          'immio_upload_position' => '0',
          'insert' => 0,
          'insert_absolute' => 0,
          'insert_class' => '',
          'insert_default' => 'auto',
          'insert_styles' => array(
            'auto' => 'auto',
            'colorbox__cheap_dropshadow' => 0,
            'colorbox__corners_combo' => 0,
            'colorbox__default' => 0,
            'colorbox__keyword_positioning' => 0,
            'colorbox__large' => 0,
            'colorbox__medium' => 0,
            'colorbox__positioned_underlay' => 0,
            'colorbox__relative_canvas' => 0,
            'colorbox__rotate_alpha' => 0,
            'colorbox__rotate_alpha_gif' => 0,
            'colorbox__rotate_scale' => 0,
            'colorbox__rotate_scale_alpha' => 0,
            'colorbox__rounded' => 0,
            'colorbox__rounded_bl' => 0,
            'colorbox__rounded_flattened' => 0,
            'colorbox__scale' => 0,
            'colorbox__scale_canvas' => 0,
            'colorbox__scale_rotate' => 0,
            'colorbox__thumbnail' => 0,
            'colorbox__watermark_100' => 0,
            'colorbox__watermark_50' => 0,
            'icon_link' => 0,
            'image' => 0,
            'image_cheap_dropshadow' => 0,
            'image_corners_combo' => 0,
            'image_default' => 0,
            'image_keyword_positioning' => 0,
            'image_large' => 0,
            'image_medium' => 0,
            'image_positioned_underlay' => 0,
            'image_relative_canvas' => 0,
            'image_rotate_alpha' => 0,
            'image_rotate_alpha_gif' => 0,
            'image_rotate_scale' => 0,
            'image_rotate_scale_alpha' => 0,
            'image_rounded' => 0,
            'image_rounded_bl' => 0,
            'image_rounded_flattened' => 0,
            'image_scale' => 0,
            'image_scale_canvas' => 0,
            'image_scale_rotate' => 0,
            'image_thumbnail' => 0,
            'image_watermark_100' => 0,
            'image_watermark_50' => 0,
            'link' => 0,
          ),
          'insert_width' => '',
          'paintweb_enabled' => 0,
          'paintweb_position' => '0',
          'picmonkey_enabled' => 0,
          'picmonkey_position' => '0',
          'pixlr_editor_enabled' => 0,
          'pixlr_editor_position' => '0',
          'pixlr_express_enabled' => 0,
          'pixlr_express_position' => '0',
          'pixlr_upload_enabled' => 0,
          'pixlr_upload_position' => '0',
          'preview_image_style' => 'thumbnail',
          'progress_indicator' => 'throbber',
          'snipshot_enabled' => 0,
          'snipshot_position' => '0',
          'sumopaint_enabled' => 0,
          'sumopaint_position' => '0',
          'svgedit_enabled' => 0,
          'svgedit_position' => '0',
        ),
        'type' => 'image_image',
        'weight' => '12',
      ),
    ),
  );

  // Exported field: 'node-our_partners-field_website'.
  $fields['node-our_partners-field_website'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_website',
      'foreign keys' => array(),
      'indexes' => array(),
      'locked' => '0',
      'module' => 'link',
      'settings' => array(
        'attributes' => array(
          'class' => '',
          'rel' => '',
          'target' => 'default',
        ),
        'display' => array(
          'url_cutoff' => 80,
        ),
        'enable_tokens' => 1,
        'title' => 'optional',
        'title_maxlength' => 128,
        'title_value' => '',
        'url' => 0,
      ),
      'translatable' => '0',
      'type' => 'link_field',
    ),
    'field_instance' => array(
      'bundle' => 'our_partners',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'link',
          'settings' => array(),
          'type' => 'link_default',
          'weight' => '1',
        ),
        'teaser' => array(
          'label' => 'above',
          'module' => 'link',
          'settings' => array(),
          'type' => 'link_url',
          'weight' => '2',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_website',
      'label' => 'Website',
      'required' => FALSE,
      'settings' => array(
        'attributes' => array(
          'class' => '',
          'rel' => '',
          'target' => 'default',
        ),
        'display' => array(
          'url_cutoff' => 80,
        ),
        'enable_tokens' => 1,
        'title' => 'optional',
        'title_maxlength' => 128,
        'title_value' => '',
        'url' => 0,
        'user_register_form' => FALSE,
        'validate_url' => 1,
      ),
      'widget' => array(
        'module' => 'link',
        'settings' => array(),
        'type' => 'link_field',
        'weight' => '6',
      ),
    ),
  );

  // Exported field: 'node-our_partners-meta_description'.
  $fields['node-our_partners-meta_description'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'meta_description',
      'foreign keys' => array(),
      'indexes' => array(),
      'locked' => '0',
      'module' => 'metatags_quick',
      'settings' => array(
        'max_length' => '160',
        'meta_name' => 'description',
      ),
      'translatable' => '0',
      'type' => 'metatags_quick',
    ),
    'field_instance' => array(
      'bundle' => 'our_partners',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'metatags_quick',
          'settings' => array(),
          'type' => 'metatags_quick_default',
          'weight' => '6',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '4',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'meta_description',
      'formatter' => 'metatags_quick_default',
      'label' => '(Meta)Description',
      'required' => FALSE,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'module' => 'metatags_quick',
        'settings' => array(),
        'type' => 'metatags_quick_textarea',
        'weight' => '11',
      ),
    ),
  );

  // Exported field: 'node-our_partners-meta_keywords'.
  $fields['node-our_partners-meta_keywords'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'meta_keywords',
      'foreign keys' => array(),
      'indexes' => array(),
      'locked' => '0',
      'module' => 'metatags_quick',
      'settings' => array(
        'max_length' => '160',
        'meta_name' => 'keywords',
      ),
      'translatable' => '0',
      'type' => 'metatags_quick',
    ),
    'field_instance' => array(
      'bundle' => 'our_partners',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'metatags_quick',
          'settings' => array(),
          'type' => 'metatags_quick_default',
          'weight' => '7',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '3',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'meta_keywords',
      'formatter' => 'metatags_quick_default',
      'label' => '(Meta)Keywords',
      'required' => FALSE,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'module' => 'metatags_quick',
        'settings' => array(),
        'type' => 'metatags_quick_textfield',
        'weight' => '10',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('(Meta)Description');
  t('(Meta)Keywords');
  t('Address');
  t('Description of Partnership');
  t('Email');
  t('Industry');
  t('Logo');
  t('Phone Number');
  t('Screenshot');
  t('Website');

  return $fields;
}
